# 31 march 2019

jobs:

- job: linux-amd64-shared
  displayName: 'Linux 64-bit shared'
  pool:
    vmImage: 'ubuntu-16.04'
  workspace:
    clean: all
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
  - script: |
      sudo apt-get install libgtk-3-dev ninja-build
      # Ubuntu typically comes with an outdated meson
      python -m pip install --upgrade pip setuptools wheel
      pip install meson
    displayName: 'Setup'
  - script: |
      meson setup build --buildtype=release --default-library=shared --backend=ninja
    displayName: 'Configure'
  - script: |
      ninja -C build
    displayName: 'Build'

- job: linux-amd64-static
  displayName: 'Linux 64-bit static'
  pool:
    vmImage: 'ubuntu-16.04'
  workspace:
    clean: all
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
  - script: |
      sudo apt-get install libgtk-3-dev ninja-build
      # Ubuntu typically comes with an outdated meson
      python -m pip install --upgrade pip setuptools wheel
      pip install meson
    displayName: 'Setup'
  - script: |
      meson setup build --buildtype=release --default-library=static --backend=ninja
    displayName: 'Configure'
  - script: |
      ninja -C build
    displayName: 'Build'

- job: windows-amd64-msvc2017-shared-msbuild
  displayName: 'Windows 64-bit MSVC2017 Shared with MSBuild'
  pool:
    vmImage: 'vs2017-win2016'
  workspace:
    clean: all
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
  - script: |
      python -m pip install --upgrade pip setuptools wheel
      pip install meson
    displayName: 'Setup'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      meson setup build --buildtype=release --default-library=shared --backend=vs2017
    displayName: 'Configure'
  - task: MSBuild@1
    inputs:
      solution: 'build/*.sln'
      maximumCpuCount: true
    displayName: 'Build'

- job: windows-amd64-msvc2017-static-ninja
  displayName: 'Windows 64-bit MSVC2017 Static Ninja'
  pool:
    vmImage: 'vs2017-win2016'
  workspace:
    clean: all
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
  - script: |
      choco install ninja
      python -m pip install --upgrade pip setuptools wheel
      pip install meson
    displayName: 'Setup'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      meson setup build --buildtype=release --default-library=static --backend=ninja
    displayName: 'Configure'
  - script: |
      ninja -C build
    displayName: 'Build'

#    mac:
#      imageName: 'macos-10.13'
#    windowsVS2017:
#      imageName: 'vs2017-win2016'
#    windowsVS2015:
#      imageName: 'vs2015-win2012r2'
