# 31 march 2019

jobs:
- job: linux64
  displayName: 'Linux 64-bit'
  pool:
    vmImage: 'ubuntu-16.04'
  workspace:
    clean: all
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
  - script: |
      sudo apt-get install libgtk-3-dev ninja-build
      # Ubuntu typically comes with an outdated meson
      python -m pip install --upgrade pip setuptools wheel
      pip install meson
    displayName: 'Setup'
  - script: |
      meson setup build-shared --buildtype=release
      ninja -C build-shared
    displayName: 'Build shared'
  - script: |
      meson setup build-static --buildtype=release --default-library=static
      ninja -C build-static
    displayName: "Build static"

#    mac:
#      imageName: 'macos-10.13'
#    windowsVS2017:
#      imageName: 'vs2017-win2016'
#    windowsVS2015:
#      imageName: 'vs2015-win2012r2'
