# 31 march 2019

variables:
  releaseExamples: 'controlgallery cpp-multithread datetime drawtext histogram tester timer'

jobs:
- job: linux_386_shared
  displayName: 'Linux 386 Shared'
  pool:
    vmImage: 'ubuntu-16.04'
  workspace:
    clean: all
  steps:
  - template: azure-pipelines/setup-python3.yml
  - template: azure-pipelines/install-latest-meson.yml
  - script: |
      sudo dpkg --add-architecture i386
      sudo apt-get update
      sudo apt-get install gcc-multilib g++-multilib || echo 1 # libc6-i386 libc6-dev-i386 lib32stdc++6 lib32tinfo5 lib32tinfo-dev lib32z1 lib32z1-dev || exit 1
      # Azure Pipelines ships with a patched version of this and that patch is only available on 64-bit systems, so trying to install the 32-bit versions will remove the 64-bit versions outright
      # This is a dependency of Mesa, so we'll have to downgrade to the stock distro ones :/
      llvmPackages=
      for i in libllvm6.0 clang-6.0 libclang-common-6.0-dev liblldb-6.0 liblldb-6.0-dev lld-6.0 lldb-6.0 llvm-6.0-dev python-lldb-6.0 libclang1-6.0 llvm-6.0; do llvmPackages="$llvmPackages $i=1:6.0-1ubuntu2~16.04.1"; done
      sudo apt-get install $llvmPackages; exit 1
      #for i in libllvm6.0:i386 libgl1-mea-dri:i386 libegl1-mesa:i386 libwayland-egl1-mesa:i386 libgtk-3-0:i386 libwayland-egl1:i386; do sudo apt-cache show $i ; echo ; echo '----------------' ; echo ; done
      #sudo apt-cache policy libllvm6-0:i386
      #sudo apt-get install libllvm6-0:i386
      # the ones after ninja-build fix broken dependencies of libgtk-3-0:i386
      sudo apt-get install libgtk-3-0:i386 libgtk-3-dev:i386 ninja-build # libgirepository-1.0-1:i386 libglib2.0-dev:i386 gir1.2-glib-2.0:i386 gir1.2-atk-1.0:i386 libatk1.0-dev:i386 libfreetype6-dev:i386 libfontconfig1-dev:i386 libcairo2-dev:i386 libgdk-pixbuf2.0-dev:i386 libpango1.0-dev:i386 libxft-dev:i386 libpng12-dev:i386
    displayName: 'Install Dependencies'
  - template: azure-pipelines/configure.yml
    parameters:
      beforeConfigure: export CFLAGS=-m32 CXXFLAGS=-m32 PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig
      defaultLibrary: shared
  - template: azure-pipelines/build.yml
  - template: azure-pipelines/darwinunix-artifacts.yml
    parameters:
      os: linux
      arch: 386
      libtype: shared
      libfiles: libui.so.0
      osHeader: ui_unix.h

- job: linux_386_static
  displayName: 'Linux 386 Static'
  pool:
    vmImage: 'ubuntu-16.04'
  workspace:
    clean: all
  steps:
  - script: exit 1
  - template: azure-pipelines/setup-python3.yml
  - template: azure-pipelines/install-latest-meson.yml
  - script: |
      sudo dpkg --add-architecture i386
      sudo apt-get update
      sudo apt-get install gcc-multilib g++-multilib
      # the ones after ninja-build fix broken dependencies of libgtk-3-0:i386
      sudo apt-get install libc6:i386 libc6-dev:i386 libgtk-3-0:i386 libgtk-3-dev:i386 ninja-build # libgirepository-1.0-1:i386 libglib2.0-dev:i386 gir1.2-glib-2.0:i386 gir1.2-atk-1.0:i386 libatk1.0-dev:i386 libfreetype6-dev:i386 libfontconfig1-dev:i386 libcairo2-dev:i386 libgdk-pixbuf2.0-dev:i386 libpango1.0-dev:i386 libxft-dev:i386 libpng12-dev:i386
    displayName: 'Install Dependencies'
  - template: azure-pipelines/configure.yml
    parameters:
      beforeConfigure: export CFLAGS=-m32 CXXFLAGS=-m32 PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig
      defaultLibrary: static
  - template: azure-pipelines/build.yml
  - template: azure-pipelines/darwinunix-artifacts.yml
    parameters:
      os: linux
      arch: 386
      libtype: static
      libfiles: libui.a
      osHeader: ui_unix.h
