# 31 march 2019

variables:
  examples: ['controlgallery', 'cpp-multithread', 'datetime', 'drawtext', 'histogram', 'tester', 'timer']


jobs:
- job: linux_amd64_shared_ninja
  displayName: 'Linux amd64 Shared with Ninja'
  pool:
    vmImage: 'ubuntu-16.04'
  workspace:
    clean: all
  steps:
  - template: azure-pipelines/setup-python3.yml
  - template: azure-pipelines/install-latest-meson.yml
  - script: |
      sudo apt-get install libgtk-3-dev ninja-build
    displayName: 'Install Dependencies'
  - template: azure-pipelines/configure.yml
    parameters:
      defaultLibrary: shared
      backend: ninja
  - template: azure-pipelines/build-ninja.yml
  - script: |
      pushd build/meson-out
      cp ../../ui.h ../../ui_unix.h .
      echo tar czf $(Build.ArtifactStagingDirectory)/libui-$(Build.SourceBranchName)-linux-amd64-shared.tgz libui.so.0 ui.h ui_unix.h
      echo tar czf $(Build.ArtifactStagingDirectory)/examples-$(Build.SourceBranchName)-linux-amd64-shared.tgz $[join(' ', variables.examples)]
      rm ui.h ui_unix.h
      popd
    displayName: 'Create Artifacts'
