# 31 march 2019

jobs:
- job: linux_amd64_shared_ninja
  displayName: 'Linux amd64 Shared with Ninja'
  pool:
    vmImage: 'ubuntu-16.04'
  workspace:
    clean: all
  steps:
  # Ubuntu typically comes with an outdated meson
  - template: azure-pipelines/install-latest-meson.yml
  - script: |
      sudo apt-get install libgtk-3-dev ninja-build
    displayName: 'Install Dependencies'
  - script: |
      meson setup build --buildtype=release --default-library=shared --backend=ninja
    displayName: 'Configure'
  - script: |
      ninja -C build
    displayName: 'Build'

- job: linux_amd64_static_ninja
  displayName: 'Linux amd64 Static with Ninja'
  pool:
    vmImage: 'ubuntu-16.04'
  workspace:
    clean: all
  steps:
  - template: azure-pipelines/install-latest-meson.yml
  - script: |
      sudo apt-get install libgtk-3-dev ninja-build
    displayName: 'Install Dependencies'
  - script: |
      meson setup build --buildtype=release --default-library=static --backend=ninja
    displayName: 'Configure'
  - script: |
      ninja -C build
    displayName: 'Build'

# TODO should it be "etc.bat" amd64 or "etc.bat amd64"?

# vs2015 {

- job: windows_386_msvc2015_shared_ninja
  displayName: 'Windows 386 MSVC2015 Shared Ninja'
  pool:
    vmImage: 'vs2015-win2012r2'
  workspace:
    clean: all
  steps:
  - template: azure-pipelines/vs2015-install-latest-python3-meson.yml
  - script: |
      choco install ninja
    displayName: 'Install Dependencies'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat x86"
      meson setup build --buildtype=release --default-library=shared --backend=ninja
    displayName: 'Configure'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat x86"
      ninja -C build
    displayName: 'Build'

- job: windows_386_msvc2015_static_ninja
  displayName: 'Windows 386 MSVC2015 Static Ninja'
  pool:
    vmImage: 'vs2015-win2012r2'
  workspace:
    clean: all
  steps:
  - template: azure-pipelines/vs2015-install-latest-python3-meson.yml
  - script: |
      choco install ninja
    displayName: 'Install Dependencies'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat x86"
      meson setup build --buildtype=release --default-library=static --backend=ninja
    displayName: 'Configure'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat x86"
      ninja -C build
    displayName: 'Build'

- job: windows_386_msvc2015_shared_msbuild
  displayName: 'Windows 386 MSVC2015 Shared with MSBuild'
  pool:
    vmImage: 'vs2015-win2012r2'
  workspace:
    clean: all
  steps:
  - template: azure-pipelines/vs2015-install-latest-python3-meson.yml
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat x86"
      meson setup build --buildtype=release --default-library=shared --backend=vs2015
    displayName: 'Configure'
  - task: MSBuild@1
    inputs:
      solution: 'build/*.sln'
      maximumCpuCount: true
    displayName: 'Build'

- job: windows_386_msvc2015_static_msbuild
  displayName: 'Windows 386 MSVC2015 Static with MSBuild'
  pool:
    vmImage: 'vs2015-win2012r2'
  workspace:
    clean: all
  steps:
  - template: azure-pipelines/vs2015-install-latest-python3-meson.yml
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat x86"
      meson setup build --buildtype=release --default-library=static --backend=vs2015
    displayName: 'Configure'
  - task: MSBuild@1
    inputs:
      solution: 'build/*.sln'
      maximumCpuCount: true
    displayName: 'Build'

- job: windows_amd64_msvc2015_shared_ninja
  displayName: 'Windows amd64 MSVC2015 Shared Ninja'
  pool:
    vmImage: 'vs2015-win2012r2'
  workspace:
    clean: all
  steps:
  - template: azure-pipelines/vs2015-install-latest-python3-meson.yml
  - script: |
      choco install ninja
    displayName: 'Install Dependencies'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat amd64"
      meson setup build --buildtype=release --default-library=shared --backend=ninja
    displayName: 'Configure'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat amd64"
      ninja -C build
    displayName: 'Build'

- job: windows_amd64_msvc2015_static_ninja
  displayName: 'Windows amd64 MSVC2015 Static Ninja'
  pool:
    vmImage: 'vs2015-win2012r2'
  workspace:
    clean: all
  steps:
  - template: azure-pipelines/vs2015-install-latest-python3-meson.yml
  - script: |
      choco install ninja
    displayName: 'Install Dependencies'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat amd64"
      meson setup build --buildtype=release --default-library=static --backend=ninja
    displayName: 'Configure'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat amd64"
      ninja -C build
    displayName: 'Build'

- job: windows_amd64_msvc2015_shared_msbuild
  displayName: 'Windows amd64 MSVC2015 Shared with MSBuild'
  pool:
    vmImage: 'vs2015-win2012r2'
  workspace:
    clean: all
  steps:
  - template: azure-pipelines/vs2015-install-latest-python3-meson.yml
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat amd64"
      meson setup build --buildtype=release --default-library=shared --backend=vs2015
    displayName: 'Configure'
  - task: MSBuild@1
    inputs:
      solution: 'build/*.sln'
      maximumCpuCount: true
    displayName: 'Build'

- job: windows_amd64_msvc2015_static_msbuild
  displayName: 'Windows amd64 MSVC2015 Static with MSBuild'
  pool:
    vmImage: 'vs2015-win2012r2'
  workspace:
    clean: all
  steps:
  - template: azure-pipelines/vs2015-install-latest-python3-meson.yml
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat amd64"
      meson setup build --buildtype=release --default-library=static --backend=vs2015
    displayName: 'Configure'
  - task: MSBuild@1
    inputs:
      solution: 'build/*.sln'
      maximumCpuCount: true
    displayName: 'Build'

# }

- job: windows_386_msvc2017_shared_ninja
  displayName: 'Windows 386 MSVC2017 Shared Ninja'
  pool:
    vmImage: 'vs2017-win2016'
  workspace:
    clean: all
  steps:
  - template: azure-pipelines/install-latest-meson.yml
  - script: |
      choco install ninja
    displayName: 'Install Dependencies'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat x86"
      meson setup build --buildtype=release --default-library=shared --backend=ninja
    displayName: 'Configure'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat x86"
      ninja -C build
    displayName: 'Build'

- job: windows_386_msvc2017_static_ninja
  displayName: 'Windows 386 MSVC2017 Static Ninja'
  pool:
    vmImage: 'vs2017-win2016'
  workspace:
    clean: all
  steps:
  - template: azure-pipelines/install-latest-meson.yml
  - script: |
      choco install ninja
    displayName: 'Install Dependencies'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat x86"
      meson setup build --buildtype=release --default-library=static --backend=ninja
    displayName: 'Configure'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat x86"
      ninja -C build
    displayName: 'Build'

- job: windows_386_msvc2017_shared_msbuild
  displayName: 'Windows 386 MSVC2017 Shared with MSBuild'
  pool:
    vmImage: 'vs2017-win2016'
  workspace:
    clean: all
  steps:
  - template: azure-pipelines/install-latest-meson.yml
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat x86"
      meson setup build --buildtype=release --default-library=shared --backend=vs2017
    displayName: 'Configure'
  - task: MSBuild@1
    inputs:
      solution: 'build/*.sln'
      maximumCpuCount: true
    displayName: 'Build'

- job: windows_386_msvc2017_static_msbuild
  displayName: 'Windows 386 MSVC2017 Static with MSBuild'
  pool:
    vmImage: 'vs2017-win2016'
  workspace:
    clean: all
  steps:
  - template: azure-pipelines/install-latest-meson.yml
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat x86"
      meson setup build --buildtype=release --default-library=static --backend=vs2017
    displayName: 'Configure'
  - task: MSBuild@1
    inputs:
      solution: 'build/*.sln'
      maximumCpuCount: true
    displayName: 'Build'

- job: windows_amd64_msvc2017_shared_ninja
  displayName: 'Windows amd64 MSVC2017 Shared Ninja'
  pool:
    vmImage: 'vs2017-win2016'
  workspace:
    clean: all
  steps:
  - template: azure-pipelines/install-latest-meson.yml
  - script: |
      choco install ninja
    displayName: 'Install Dependencies'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64"
      meson setup build --buildtype=release --default-library=shared --backend=ninja
    displayName: 'Configure'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64"
      ninja -C build
    displayName: 'Build'

- job: windows_amd64_msvc2017_static_ninja
  displayName: 'Windows amd64 MSVC2017 Static Ninja'
  pool:
    vmImage: 'vs2017-win2016'
  workspace:
    clean: all
  steps:
  - template: azure-pipelines/install-latest-meson.yml
  - script: |
      choco install ninja
    displayName: 'Install Dependencies'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64"
      meson setup build --buildtype=release --default-library=static --backend=ninja
    displayName: 'Configure'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64"
      ninja -C build
    displayName: 'Build'

- job: windows_amd64_msvc2017_shared_msbuild
  displayName: 'Windows amd64 MSVC2017 Shared with MSBuild'
  pool:
    vmImage: 'vs2017-win2016'
  workspace:
    clean: all
  steps:
  - template: azure-pipelines/install-latest-meson.yml
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64"
      meson setup build --buildtype=release --default-library=shared --backend=vs2017
    displayName: 'Configure'
  - task: MSBuild@1
    inputs:
      solution: 'build/*.sln'
      maximumCpuCount: true
    displayName: 'Build'

- job: windows_amd64_msvc2017_static_msbuild
  displayName: 'Windows amd64 MSVC2017 Static with MSBuild'
  pool:
    vmImage: 'vs2017-win2016'
  workspace:
    clean: all
  steps:
  - template: azure-pipelines/install-latest-meson.yml
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64"
      meson setup build --buildtype=release --default-library=static --backend=vs2017
    displayName: 'Configure'
  - task: MSBuild@1
    inputs:
      solution: 'build/*.sln'
      maximumCpuCount: true
    displayName: 'Build'

#    mac:
#      imageName: 'macos-10.13'
#    windowsVS2017:
#      imageName: 'vs2017-win2016'
#    windowsVS2015:
#      imageName: 'vs2015-win2012r2'
