# 31 march 2019

variables:
  releaseExamples: 'controlgallery cpp-multithread datetime drawtext histogram tester timer'

jobs:
- job: linux_386_shared
  displayName: 'Linux 386 Shared'
  pool:
    vmImage: 'ubuntu-16.04'
  workspace:
    clean: all
  steps:
  - template: azure-pipelines/setup-python3.yml
  - template: azure-pipelines/install-latest-meson.yml
  - script: |
      sudo dpkg --add-architecture :i386
      sudo apt-get update
      sudo apt-get install libc-dev-i386 gcc-multilib g++-multilib
      # the ones after ninja-build fix broken dependencies of libgtk-3-0:i386
      sudo apt-get install libgtk-3-dev:i386 ninja-build libgirepository-1.0-1:i386 libglib2.0-dev:i386 gir1.2-glib-2.0:i386 gir1.2-atk-1.0:i386 libatk1.0-dev:i386 libfreetype6-dev:i386 libfontconfig1-dev:i386 libcairo2-dev:i386 libgdk-pixbuf2.0-dev:i386 libpango1.0-dev:i386 libxft-dev:i386 libpng12-dev:i386
    displayName: 'Install Dependencies'
  - template: azure-pipelines/configure.yml
    parameters:
      beforeConfigure: export CFLAGS=-m32 CXXFLAGS=-m32 PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig
      defaultLibrary: shared
  - template: azure-pipelines/build.yml
  - template: azure-pipelines/darwinunix-artifacts.yml
    parameters:
      os: linux
      arch: 386
      libtype: shared
      libfiles: libui.so.0
      osHeader: ui_unix.h

- job: linux_386_static
  displayName: 'Linux 386 Static'
  pool:
    vmImage: 'ubuntu-16.04'
  workspace:
    clean: all
  steps:
  - template: azure-pipelines/setup-python3.yml
  - template: azure-pipelines/install-latest-meson.yml
  - script: |
      sudo dpkg --add-architecture :i386
      sudo apt-get update
      sudo apt-get install libc-dev-i386 gcc-multilib g++-multilib
      # the ones after ninja-build fix broken dependencies of libgtk-3-0:i386
      sudo apt-get install libgtk-3-dev:i386 ninja-build libgirepository-1.0-1:i386 libglib2.0-dev:i386 gir1.2-glib-2.0:i386 gir1.2-atk-1.0:i386 libatk1.0-dev:i386 libfreetype6-dev:i386 libfontconfig1-dev:i386 libcairo2-dev:i386 libgdk-pixbuf2.0-dev:i386 libpango1.0-dev:i386 libxft-dev:i386 libpng12-dev:i386
    displayName: 'Install Dependencies'
  - template: azure-pipelines/configure.yml
    parameters:
      beforeConfigure: export CFLAGS=-m32 CXXFLAGS=-m32 PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig
      defaultLibrary: static
  - template: azure-pipelines/build.yml
  - template: azure-pipelines/darwinunix-artifacts.yml
    parameters:
      os: linux
      arch: 386
      libtype: static
      libfiles: libui.a
      osHeader: ui_unix.h
