# 31 march 2019

variables:
  releaseExamples: 'controlgallery cpp-multithread datetime drawtext histogram tester timer'

jobs:
- job: darwin_amd64_1014sdk_shared
  displayName: 'Darwin amd64 10.14 SDK Shared'
  pool:
    vmImage: 'macos-10.13'
  workspace:
    clean: all
  steps:
  - template: azure-pipelines/setup-python3.yml
  - template: azure-pipelines/install-latest-meson.yml
  - template: azure-pipelines/darwin-install-ninja.yml
  - script: |
      xcodebuild -showsdks
      exit 1
    displayName: "Help"
  - template: azure-pipelines/configure.yml
    parameters:
      beforeConfigure: export SDKROOT=$(xcodebuild -version -sdk macosx10.14 Path)
      defaultLibrary: shared
  - template: azure-pipelines/build.yml
    parameters:
      beforeBuild: export SDKROOT=$(xcodebuild -version -sdk macosx10.14 Path)
  - template: azure-pipelines/darwinunix-artifacts.yml
    parameters:
      os: darwin
      arch: amd64
      libtype: shared
      libfiles: libui.A.dylib
      osHeader: ui_darwin.h
