# 31 march 2019

jobs:
- job: linux64
  displayName: 'Linux 64-bit'
  pool:
    vmImage: 'ubuntu-16.04'
  workspace:
    clean: all
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
  - script: |
      sudo apt-get install libgtk-3-dev ninja-build
      # Ubuntu typically comes with an outdated meson
      python -m pip install --upgrade pip setuptools wheel
      pip install meson
    displayName: 'Setup'
  - script: |
      meson setup build-shared --buildtype=release
      ninja -C build-shared
    displayName: 'Build shared'
  - script: |
      meson setup build-static --buildtype=release --default-library=static
      ninja -C build-static
    displayName: 'Build static'

- job: windowsVS2017Msbuild
  displayName: 'Windows 64-bit Visual Studio 2017'
  pool:
    vmImage: 'vs2017-win2016'
  workspace:
    clean: all
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
  - script: |
      python -m pip install --upgrade pip setuptools wheel
      pip install meson
    displayName: 'Setup'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      meson setup build-shared --buildtype=release --backend=vs2017
    displayName: 'Prepare shared build'
  - task: MSBuild@1
    inputs:
      solution: 'build-shared/*.sln'
      maximumCpuCount: true
    displayName: 'Build shared'
  - script: |
      meson setup build-static --buildtype=release --default-library=static --backend=vs2017
    displayName: 'Prepare static build'
  - task: MSBuild@1
    inputs:
      solution: 'build-static/*.sln'
      maximumCpuCount: true
    displayName: 'Build static'

#    mac:
#      imageName: 'macos-10.13'
#    windowsVS2017:
#      imageName: 'vs2017-win2016'
#    windowsVS2015:
#      imageName: 'vs2015-win2012r2'
