# 4 april 2019

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'
- script: |
    python -m pip install --upgrade pip setuptools wheel
    pip install meson
  displayName: 'Install Latest Meson'
