# 7 april 2019

parameters:
  which: 'must-be-specified'

steps:
- powershell: |
    $chocopath = where.exe choco.exe | Get-Item
    $chocopath = Join-Path $chocopath.Directory "install" "${{ parameters.which }}" "bin"
    echo "##vso[task.prependpath]$chocopath"
  displayName: 'Set Up MinGW-w64'
